"""
Git Commit Tracking Constants
All commit categories, priorities, emojis, and keywords
"""

from typing import TypedDict


# Type definition for category information
class CategoryInfo(TypedDict):
    priority: int
    emoji: str
    keywords: list[str]


# Commit categories with priority and keywords
# Higher priority = more important category
COMMIT_CATEGORIES: dict[str, CategoryInfo] = {
    "revert": {
        "priority": 100,
        "emoji": "⏪",
        "keywords": [
            "revert",
            "rollback",
            "undo",
            "back out",
            "backout",
            "rewind",
            "restore",
            "reset",
            "reverse",
            "unmerge",
        ],
    },
    "security": {
        "priority": 95,
        "emoji": "🔒",
        "keywords": [
            "security",
            "vulnerability",
            "cve",
            "auth",
            "authentication",
            "authorization",
            "permission",
            "permissions",
            "access",
            "encryption",
            "encrypt",
            "decrypt",
            "ssl",
            "tls",
            "https",
            "certificate",
            "cert",
            "token",
            "password",
            "secret",
            "secrets",
            "leak",
            "exposure",
            "sanitize",
            "escape",
            "injection",
            "xss",
            "csrf",
            "sqli",
            "exploit",
            "patch security",
            "security fix",
            "secure",
            "harden",
            "hardening",
        ],
    },
    "fix": {
        "priority": 90,
        "emoji": "🐛",
        "keywords": [
            "fix",
            "fixed",
            "fixes",
            "bugfix",
            "hotfix",
            "patch",
            "bug",
            "resolve",
            "resolved",
            "resolves",
            "solved",
            "solve",
            "issue",
            "error",
            "crash",
            "broken",
            "fault",
            "mistake",
            "correct",
            "repair",
            "handle",
            "prevent",
            "avoid",
            "typo",
            "oops",
            "troubleshoot",
            "debug",
            "debugging",
            "debugged",
            "workaround",
            "mitigate",
            "mitigation",
            "address",
            "addressed",
            "addresses",
            "remedy",
            "remediate",
            "correction",
            "glitch",
            "defect",
        ],
    },
    "feat": {
        "priority": 80,
        "emoji": "✨",
        "keywords": [
            "feat",
            "feature",
            "add",
            "added",
            "adds",
            "new",
            "implement",
            "implemented",
            "introduce",
            "introduced",
            "create",
            "created",
            "enhance",
            "enhanced",
            "extend",
            "support",
            "enable",
            "allow",
            "integrate",
            "develop",
            "include",
            "provide",
            "setup",
            "capability",
            "functionality",
            "improvement",
            "innovation",
            "addition",
            "establish",
            "build",
            "construct",
            "design",
        ],
    },
    "accessibility": {
        "priority": 75,
        "emoji": "♿",
        "keywords": [
            "a11y",
            "accessibility",
            "accessible",
            "aria",
            "wcag",
            "screen reader",
            "screenreader",
            "keyboard",
            "keyboard navigation",
            "contrast",
            "alt text",
            "alt",
            "alternative text",
            "semantic",
            "focus",
            "tab order",
            "tabindex",
            "assistive",
            "disability",
            "inclusive",
            "usability",
            "voice",
            "blind",
            "deaf",
            "impair",
            "handicap",
            "ada",
            "compliance",
            "section 508",
        ],
    },
    "perf": {
        "priority": 70,
        "emoji": "⚡",
        "keywords": [
            "perf",
            "performance",
            "optimize",
            "optimized",
            "optimization",
            "faster",
            "speed",
            "speedup",
            "improve",
            "boost",
            "accelerate",
            "efficient",
            "reduce",
            "decreased",
            "cache",
            "lazy",
            "quick",
            "enhance performance",
            "reduce memory",
            "reduce time",
            "throttle",
            "debounce",
            "memoize",
            "memoization",
            "parallelize",
            "parallel",
            "async",
            "asynchronous",
            "concurrent",
            "streaming",
            "buffer",
            "batch",
            "lightweight",
            "minimize",
            "shrink",
        ],
    },
    "i18n": {
        "priority": 65,
        "emoji": "🌍",
        "keywords": [
            "i18n",
            "l10n",
            "internationalization",
            "localization",
            "translation",
            "translate",
            "translated",
            "locale",
            "locales",
            "language",
            "languages",
            "multilingual",
            "multilanguage",
            "globalization",
            "regionalization",
            "culture",
            "cultures",
            "rtl",
            "ltr",
            "bidi",
            "unicode",
            "charset",
            "encoding",
            "locale-specific",
            "country",
            "region",
            "timezone",
        ],
    },
    "refactor": {
        "priority": 60,
        "emoji": "🔧",
        "keywords": [
            "refactor",
            "refactored",
            "refactoring",
            "restructure",
            "rewrite",
            "rework",
            "simplify",
            "extract",
            "move",
            "moved",
            "rename",
            "renamed",
            "reorganize",
            "clean",
            "cleanup",
            "improve",
            "decouple",
            "abstract",
            "consolidate",
            "deduplicate",
            "modularize",
            "split",
            "modernize",
            "streamline",
            "normalize",
            "standardize",
            "unify",
            "dry",
            "optimize structure",
            "reduce complexity",
            "clarify",
            "tidy",
            "polish",
            "revise",
            "rearrange",
            "redesign",
        ],
    },
    "deprecation": {
        "priority": 55,
        "emoji": "⚠️",
        "keywords": [
            "deprecate",
            "deprecated",
            "deprecating",
            "deprecation",
            "obsolete",
            "obsoleted",
            "legacy",
            "remove deprecated",
            "sunset",
            "sunsetting",
            "end-of-life",
            "eol",
            "retire",
            "retired",
            "retiring",
            "phase out",
            "phasing out",
            "discontinue",
            "discontinued",
            "supersede",
            "superseded",
            "replace deprecated",
            "old api",
            "legacy code",
            "backward compatible",
            "breaking change",
        ],
    },
    "test": {
        "priority": 50,
        "emoji": "🧪",
        "keywords": [
            "test",
            "tests",
            "testing",
            "spec",
            "specs",
            "coverage",
            "unit",
            "integration",
            "e2e",
            "jest",
            "pytest",
            "mock",
            "stub",
            "fixture",
            "assertion",
            "expect",
            "should",
            "verify",
            "validate",
            "check",
            "ensure",
            "prove",
            "tdd",
            "bdd",
            "snapshot",
            "regression",
            "smoke test",
            "smoke",
            "sanity check",
            "sanity",
            "acceptance",
            "functional",
            "scenario",
            "suite",
            "testcase",
            "test case",
            "qa",
            "quality assurance",
        ],
    },
    "build": {
        "priority": 40,
        "emoji": "📦",
        "keywords": [
            "build",
            "compile",
            "bundle",
            "webpack",
            "rollup",
            "vite",
            "make",
            "cmake",
            "gradle",
            "maven",
            "npm",
            "yarn",
            "pnpm",
            "package",
            "dist",
            "transpile",
            "babel",
            "typescript",
            "tsc",
            "esbuild",
            "swc",
            "minify",
            "uglify",
            "compress",
        ],
    },
    "ci": {
        "priority": 30,
        "emoji": "🔄",
        "keywords": [
            "ci",
            "cd",
            "pipeline",
            "github actions",
            "actions",
            "travis",
            "jenkins",
            "circle",
            "circleci",
            "deploy",
            "deployment",
            "release",
            "publish",
            "docker",
            "kubernetes",
            "k8s",
            "helm",
            "terraform",
            "ansible",
            "workflow",
            "automation",
            "continuous",
            "staging",
            "production",
            "rollout",
            "canary",
            "blue-green",
            "artifact",
            "artifacts",
            "container",
            "orchestration",
            "infrastructure",
            "iac",
            "gitops",
            "devops",
            "cicd",
        ],
    },
    "docs": {
        "priority": 20,
        "emoji": "📚",
        "keywords": [
            "docs",
            "documentation",
            "readme",
            "comment",
            "comments",
            "javadoc",
            "jsdoc",
            "docstring",
            "api doc",
            "guide",
            "tutorial",
            "example",
            "clarify",
            "explain",
            "describe",
            "document",
            "wiki",
            "changelog",
            "notes",
            "annotation",
            "usage",
        ],
    },
    "style": {
        "priority": 10,
        "emoji": "💅",
        "keywords": [
            "style",
            "format",
            "formatting",
            "lint",
            "linting",
            "prettier",
            "eslint",
            "pylint",
            "rubocop",
            "whitespace",
            "indent",
            "indentation",
            "semicolon",
            "quotes",
            "spacing",
            "code style",
            "convention",
            "pep8",
            "black",
            "gofmt",
            "rustfmt",
            "standardize",
        ],
    },
    "chore": {
        "priority": 5,
        "emoji": "🔨",
        "keywords": [
            "chore",
            "update",
            "updated",
            "upgrade",
            "bump",
            "deps",
            "dependencies",
            "dependency",
            "version",
            "maintain",
            "routine",
            "housekeeping",
            "misc",
            "minor",
            "tweak",
            "adjust",
            "modify",
            "prepare",
            "setup",
            "config",
            "configure",
            "init",
            "bootstrap",
        ],
    },
    "merge": {
        "priority": 1,
        "emoji": "🔄",
        "keywords": [
            "merge",
            "merged",
            "merging",
            "merge branch",
            "merge pull",
            "merge pr",
            "merge conflict",
            "resolve conflict",
            "conflict",
            "rebase",
            "rebased",
            "rebasing",
            "cherry-pick",
            "cherry pick",
            "cherrypick",
            "squash",
            "squashed",
            "integrate branch",
        ],
    },
    "wip": {
        "priority": 0,
        "emoji": "🚧",
        "keywords": [
            "wip",
            "work in progress",
            "working",
            "todo",
            "temp",
            "tmp",
            "temporary",
            "hack",
            "xxx",
            "fixme",
            "fix me",
            "draft",
            "incomplete",
            "unfinished",
            "in progress",
            "partial",
            "checkpoint",
            "savepoint",
            "do not merge",
            "dont merge",
            "not ready",
            "experimental",
            "experiment",
        ],
    },
}

# Default category for uncategorized commits
DEFAULT_CATEGORY = "other"
DEFAULT_EMOJI = "📝"
