"""PathWise Tips and Hints - Educational content for users"""

TIPS = {
    "pathwise": [
        "Use 'wj1' through 'wj5' to jump to your most visited directories instantly",
        "Run 'wfreq --insights' to see detailed analytics about your navigation patterns",
        "PathWise tracks time automatically - stay in a directory 5+ seconds to record it",
        "Use 'wfreq --config' to customize tracking settings and display preferences",
        "Your jump shortcuts update dynamically as your habits change throughout the day",
        "Run 'wfreq --reset' to clear all data and start fresh with new tracking",
        "PathWise rotates data daily at midnight - yesterday becomes your fallback",
        "Enable git tracking to see what type of work you do in each directory",
        "Sort by 'time' to see where you spend most time, or 'visits' for frequency",
        "PathWise learns your patterns - the more you navigate, the smarter it gets",
        "Check 'wfreq --insights' weekly to understand your productivity patterns",
        "Jump shortcuts persist across terminal sessions until your habits change",
        "Use PathWise data to identify time sinks and optimize your workflow",
        "PathWise tracks both visits and time - giving you complete navigation insights",
        "Configure minimum time to avoid tracking quick directory traversals",
        "Use 'wfreq --tools' to see which tools you use most in each directory",
        "Tool tracking reveals your workflow - see if you edit, compile, or debug more",
        "Export your work patterns with 'wfreq --export' to share with teammates",
        "Use 'wfreq --export -filter=python' to export only Python-related project data",
        "Export current project with 'wfreq --export project.toml -filter=.' for focused reports",
        "TOML exports show WHERE you use each tool - perfect for onboarding new developers",
        "Share your exported TOML with teammates to demonstrate project workflows",
        "Filter exports by directory patterns to create focused work analytics",
        "Exported TOML files contain all your insights: time patterns, tools, and navigation flows",
    ],
    "zsh": [
        "Use 'cd -' to quickly jump back to your previous directory",
        "Press Ctrl+R to search through your command history interactively",
        "Use '!!' to repeat the last command, or 'sudo !!' to run it with sudo",
        "Tab completion works for commands, files, and even git branches",
        "Use 'cd **/<tab>' to fuzzy search for directories recursively",
        "Create permanent aliases in ~/.zshrc for your common commands",
        "Use 'which <command>' to find where a command is located",
        "Press Alt+. to insert the last argument from previous command",
        "Use 'dirs -v' to see your directory stack, 'cd ~N' to jump to entry N",
        "Enable case-insensitive completion: 'zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'",
        "Use 'bindkey' to see all keyboard shortcuts in your current shell",
        "Press Ctrl+L to clear the screen (faster than typing 'clear')",
        "Use 'fc' to edit and re-run the last command in your editor",
        "Set CDPATH to add common base directories for quick navigation",
        "Use parameter expansion: ${var:-default} for default values",
    ],
    "linux": [
        "Use 'ls -lah' to see all files with human-readable sizes",
        "Press Ctrl+Z to suspend a process, 'bg' to background it, 'fg' to foreground",
        "Use 'df -h' to check disk space, 'du -sh *' for directory sizes",
        "The 'tree' command shows directory structure visually (install if needed)",
        "Use 'grep -r \"pattern\" .' to search recursively in current directory",
        "Press Ctrl+D to logout or exit (cleaner than typing 'exit')",
        "Use 'ps aux | grep <name>' to find processes, 'kill -9 <pid>' to force stop",
        "The 'watch' command repeats any command periodically: 'watch -n 2 ls'",
        "Use 'chmod +x file' to make a file executable quickly",
        "Redirect errors with '2>' or both output and errors with '&>'",
        "Use 'find . -name \"*.txt\" -mtime -7' to find files modified in last 7 days",
        "The 'tee' command shows output and saves it: 'ls | tee output.txt'",
        "Use 'tail -f logfile' to watch a log file in real-time",
        "Create multiple directories at once: 'mkdir -p parent/child/grandchild'",
        "Use 'ln -s target link' to create symbolic links for easy access",
    ],
    "productivity": [
        "Organize projects in a consistent directory structure for faster navigation",
        "Use descriptive directory names - future you will thank present you",
        "Keep your home directory clean - use subdirectories for organization",
        "Create a ~/tmp directory for temporary work that you clean regularly",
        "Use version control (git) in all project directories for safety",
        "Batch similar tasks together to reduce context switching",
        "Review your PathWise insights weekly to optimize your workflow",
        "Set up project templates to standardize new project creation",
        "Use meaningful commit messages - they're documentation for future you",
        "Take breaks - productivity isn't about time spent but work accomplished",
        "Document your setup and workflows in a personal knowledge base",
        "Automate repetitive tasks with shell scripts or aliases",
        "Use virtual environments for Python projects to avoid conflicts",
        "Keep a 'notes.md' file in project roots for quick thoughts",
        "Learn keyboard shortcuts for your most-used applications",
    ],
    "git": [
        "Use 'git status' frequently to understand your repository state",
        "Run 'git diff --staged' to review changes before committing",
        "Use 'git log --oneline --graph' for a visual commit history",
        "Create meaningful branch names: feature/what-it-does",
        "Use 'git stash' to temporarily save work when switching contexts",
        "Run 'git commit --amend' to fix the last commit message",
        "Use 'git reset HEAD~1' to undo the last commit (keeping changes)",
        "Set up git aliases: 'git config --global alias.co checkout'",
        "Use 'git blame <file>' to see who changed each line and when",
        "Run 'git clean -fd' to remove untracked files and directories",
        "Use '.gitignore' to exclude files from version control",
        "Create atomic commits - each commit should do one thing",
        "Use 'git bisect' to find which commit introduced a bug",
        "Run 'git reflog' to recover lost commits or branches",
        "Tag releases: 'git tag -a v1.0.0 -m \"Version 1.0.0\"'",
    ],
    "advanced": [
        "Use process substitution: 'diff <(ls dir1) <(ls dir2)'",
        "Chain commands: '&&' for success, '||' for failure, ';' for always",
        "Use brace expansion: 'cp file.{txt,bak}' copies file.txt to file.bak",
        "Export functions in zsh: 'typeset -f -x function_name'",
        "Use 'exec' to replace the current shell with a command",
        "Create here-documents: 'cat << EOF > file.txt'",
        "Use extended globbing: 'setopt EXTENDED_GLOB' for advanced patterns",
        "Redirect stdout and stderr separately: 'cmd 1>out.txt 2>err.txt'",
        "Use coprocesses for bidirectional communication with commands",
        "Set up zsh hooks: add_zsh_hook for preexec, precmd, chpwd",
        "Use parameter expansion for string manipulation: ${var%suffix}",
        "Create associative arrays: 'typeset -A hash' in zsh",
        "Use 'zmodload' to load additional zsh modules for extra features",
        "Profile shell startup: 'zsh -x' to debug slow initialization",
        "Use 'compdef' to create custom completions for your functions",
    ],
    "bash_strings": [
        "Trim leading/trailing spaces: '${var##+([[:space:]])}' and '${var%%+([[:space:]])}'",
        "Get string length: '${#var}' returns character count without wc",
        "Split string on delimiter: 'IFS=: read -ra arr <<< \"$PATH\"' creates array",
        "Lowercase string: '${var,,}' converts to lowercase in Bash 4+",
        "Uppercase string: '${var^^}' converts to uppercase in Bash 4+",
        "Reverse case: '${var~~}' toggles case of all characters",
        "Remove spaces: '${var// /}' deletes all spaces from string",
        "Check if string contains substring: '[[ $var == *\"text\"* ]]' pattern match",
        "Check string starts with: '[[ $var == text* ]]' prefix pattern",
        "Check string ends with: '[[ $var == *text ]]' suffix pattern",
        "Get first N chars: '${var:0:10}' extracts first 10 characters",
        "Get last N chars: '${var: -10}' extracts last 10 characters (note space)",
        "Get substring by offset: '${var:10:5}' gets 5 chars starting at position 10",
        "Strip prefix: '${var#prefix}' removes shortest prefix match",
        "Strip suffix: '${var%suffix}' removes shortest suffix match",
        "Percent-encode string: Use printf '%s' \"$var\" | od -An -tx1 | tr ' ' %",
        "Regex match: '[[ $var =~ ^[0-9]+$ ]]' checks if string is all digits",
    ],
    "bash_arrays": [
        "Reverse array: 'for ((i=${#arr[@]}-1; i>=0; i--)); do rev+=(\"${arr[i]}\"); done'",
        "Remove duplicates: Keep unique values with associative array as set",
        "Random array element: '${arr[RANDOM % ${#arr[@]}]}' picks random item",
        "Cycle through array: Use modulo '${arr[i++ % ${#arr[@]}]}' for infinite loop",
        "Toggle between values: 'var=$((1-var))' switches between 0 and 1",
    ],
    "bash_loops": [
        "Loop over range: 'for i in {1..10}; do ...; done' iterates 1 to 10",
        "Variable range: 'for ((i=start; i<=end; i++)); do ...; done' with variables",
        "Loop over array: 'for elem in \"${arr[@]}\"; do ...; done' iterates elements",
        "Loop with index: 'for i in \"${!arr[@]}\"; do echo ${arr[i]}; done'",
        "Loop file contents: 'while IFS= read -r line; do ...; done < file'",
        "Loop over files: 'for f in *.txt; do [[ -e $f ]] || continue; ...; done'",
    ],
    "bash_file_handling": [
        "Read file to string: 'var=$(<file)' faster than cat for variable assignment",
        "Read file to array: 'readarray -t arr < file' or mapfile for line array",
        "Get first line: 'IFS= read -r line < file' reads just first line",
        "Get last N lines: Store in array and print last elements for tail behavior",
        "Line count: 'while IFS= read -r _; do ((count++)); done < file'",
        "Random line: Read to array then '${arr[RANDOM % ${#arr[@]}]}'",
        "Create temp file: 'tmp=$(mktemp) || exit 1' with proper error handling",
        "Extract path parts: '${file##*/}' for basename, '${file%/*}' for dirname",
    ],
    "bash_conditionals": [
        "File tests: '[[ -f $file ]]' for regular file, '-d' for directory, '-e' exists",
        "String empty check: '[[ -z $var ]]' tests if empty, '-n' for non-empty",
        "Ternary operator: 'result=${var:+set}' expands to 'set' if var is non-empty",
        "Check if in array: Loop and test each element or use associative array",
    ],
    "bash_variables": [
        "Name reference: 'declare -n ref=var' creates reference to another variable",
        "Default value: '${var:-default}' uses default if var is unset or empty",
    ],
    "bash_arithmetic": [
        "Math operations: '((result = 5 + 3 * 2))' evaluates arithmetic expressions",
        "Sequence generation: 'for i in {1..100}; do ...; done' without seq command",
    ],
    "bash_traps": [
        "Cleanup on exit: 'trap cleanup EXIT' runs cleanup function on script exit",
        "Ignore Ctrl+C: 'trap '' INT' ignores interrupt signal (SIGINT)",
        "React to signals: 'trap \"echo Caught\" INT TERM' handles multiple signals",
        "Run in background: 'command &' runs async, 'wait' to synchronize",
        "Timeout command: Use timeout with trap for time-limited execution",
    ],
    "bash_terminal": [
        "Get terminal size: 'read -r LINES COLUMNS < <(stty size)' without tput",
        "Move cursor: 'printf '\\e[5;10H'' moves to line 5, column 10",
        "Clear screen: 'printf '\\e[2J\\e[H'' clears and homes cursor",
    ],
    "bash_internals": [
        "Get function name: '${FUNCNAME[0]}' returns current function name",
        "Get hostname: '${HOSTNAME:-$(hostname)}' without external command",
        "Brace expansion: '{1..10}' expands to '1 2 3 4 5 6 7 8 9 10'",
        "Check command type: 'type -t cmd' returns alias/function/builtin/file",
    ],
    "bash_other": [
        "UUID generation: Read from /proc/sys/kernel/random/uuid if available",
        "Progress bar: Use printf with carriage return '\\r' to update same line",
        "Get epoch: 'printf '%(%s)T' -1' in Bash 4.2+ instead of date +%s",
        "Format date: 'printf '%(%Y-%m-%d)T' -1' formats without date command",
        "Hex to RGB: Use printf '%d' 0x${hex:0:2} to convert hex color values",
        "RGB to hex: 'printf '#%02x%02x%02x' $r $g $b' converts RGB to hex",
        "Pseudo-random: '$((RANDOM % 100))' gives 0-99, seed with RANDOM=seed",
    ],
    "tmux": [
        'Split horizontally: Ctrl+b % | Split vertically: Ctrl+b "',
        "Navigate panes: Ctrl+b + arrow keys for quick pane switching",
        "Create new window: Ctrl+b c | Switch windows: Ctrl+b 0-9",
        "Detach session: Ctrl+b d | Reattach: 'tmux attach'",
        "List sessions: 'tmux ls' | Kill session: 'tmux kill-session -t name'",
        "Rename window: Ctrl+b , | Rename session: Ctrl+b $",
        "Zoom pane to fullscreen: Ctrl+b z (toggle zoom)",
        "Copy mode: Ctrl+b [ to scroll and copy text, q to exit",
        "Resize panes: Hold Ctrl+b and use arrow keys",
        "Synchronize panes: Ctrl+b : then 'setw synchronize-panes' for parallel input",
        "Save layout: Ctrl+b : then 'list-windows -F' to see layout string",
        "Search in copy mode: Ctrl+b [ then Ctrl+s (forward) or Ctrl+r (reverse)",
        "Break pane to window: Ctrl+b ! moves current pane to new window",
        "Join panes: 'join-pane -s window.pane' merges panes",
        "Persist sessions: Use 'tmux-resurrect' plugin to save/restore sessions",
    ],
    "terminal_features": [
        "Most terminals support Ctrl+Shift+T for new tab, Ctrl+Shift+W to close",
        "Click URLs: Hold Ctrl while clicking links in most modern terminals",
        "Select rectangular blocks: Hold Alt while selecting text",
        "Zoom text: Ctrl+Plus/Minus adjusts font size in most terminals",
        "Search output: Ctrl+Shift+F searches scrollback in many terminals",
        "Clear scrollback: Ctrl+Shift+K in some terminals, 'clear && printf '\\e[3J'' in others",
        "GPU rendering: Enable in preferences for smoother scrolling on high DPI",
        "True color support: Test with 'printf '\\x1b[38;2;255;100;0mTRUECOLOR\\x1b[0m\\n''",
        "Set title: 'echo -ne '\\033]0;Your Title\\007'' changes terminal window title",
        "Save output: Use 'script' command to record entire terminal session",
        "Unicode support: Modern terminals handle emoji and special chars natively 🚀",
        "Alt+click in many terminals positions cursor at click location",
        "Double-click selects word, triple-click selects entire line",
        "Middle mouse button pastes selection buffer on Linux",
        "Ctrl+L clears screen while preserving scrollback history",
    ],
    "ssh": [
        "SSH config: Create ~/.ssh/config for host aliases and settings",
        "Agent forwarding: 'ssh -A' forwards your SSH keys to remote host",
        "Port forwarding: 'ssh -L 8080:localhost:80 server' forwards remote port",
        "Reverse tunnel: 'ssh -R 9000:localhost:3000 server' exposes local port",
        "Keep alive: Add 'ServerAliveInterval 60' to ~/.ssh/config",
        "Jump hosts: 'ssh -J bastion target' or ProxyJump in config",
        "SSH keys: 'ssh-copy-id user@host' installs your public key",
        "Escape sequences: Type '~.' to disconnect hung session",
        "Compression: 'ssh -C' enables compression for slow connections",
        "X11 forwarding: 'ssh -X' allows running GUI apps remotely",
        "Control master: Share connections with ControlPath in config",
        "SOCKS proxy: 'ssh -D 8080 server' creates SOCKS5 proxy",
        "Run command: 'ssh server \"command\"' executes and returns",
        "Background tunnel: 'ssh -fNL 8080:localhost:80 server' runs in background",
        "Verbose mode: 'ssh -vvv' for debugging connection issues",
    ],
    "cli_tools": [
        "fzf: Press Ctrl+R after installing fzf for fuzzy command history search",
        "ripgrep: 'rg pattern' is faster than grep and respects .gitignore",
        "fd: 'fd pattern' is a fast, user-friendly alternative to find",
        "bat: Enhanced cat with syntax highlighting and git integration",
        "exa/eza: Modern ls replacement with tree view and git status",
        "jq: 'curl api | jq .field' extracts JSON fields elegantly",
        "htop/btop: Interactive process viewers superior to top",
        "ncdu: NCurses disk usage analyzer for finding large files",
        "tldr: Simplified man pages with practical examples",
        "ag: The Silver Searcher - another fast code searching tool",
        "httpie: 'http GET example.com' for human-friendly HTTP requests",
        "delta: Beautiful git diff viewer with syntax highlighting",
        "zoxide: Smarter cd that learns your habits (like PathWise!)",
        "direnv: Auto-load environment variables per directory",
        "entr: 'ls *.py | entr -c python main.py' auto-runs on file changes",
    ],
    "docker": [
        "Clean everything: 'docker system prune -a' removes all unused data",
        "Live logs: 'docker logs -f container' follows log output",
        "Exec into container: 'docker exec -it container bash' for debugging",
        "Copy files: 'docker cp file container:/path' transfers files",
        "Resource stats: 'docker stats' shows real-time container metrics",
        "Build with no cache: 'docker build --no-cache .' forces fresh build",
        "Remove dangling images: 'docker image prune' cleans unnamed images",
        "List with formatting: 'docker ps --format \"table {{.Names}}\\t{{.Status}}\"'",
        "Stop all containers: 'docker stop $(docker ps -q)' halts everything",
        "Volume backup: 'docker run --rm -v vol:/data -v .:/backup busybox tar czf backup.tar.gz'",
        "Multi-stage builds: Use 'FROM image AS stage' for smaller final images",
        "Health checks: Add HEALTHCHECK to Dockerfile for container monitoring",
        "Use .dockerignore: Exclude files from build context for faster builds",
        "Layer caching: Order Dockerfile commands from least to most frequently changing",
        "Network debugging: 'docker run --rm -it nicolaka/netshoot' for network tools",
    ],
    "performance": [
        "htop: Press F5 for tree view, F6 to sort by different columns",
        "iostat: 'iostat -x 1' shows detailed disk I/O statistics per second",
        "iotop: Requires sudo, shows which processes are doing disk I/O",
        "nethogs: 'sudo nethogs' displays bandwidth usage per process",
        "ss: Modern netstat - 'ss -tulpn' shows listening ports",
        "perf: 'perf top' shows real-time CPU function usage (needs root)",
        "strace: 'strace -c command' summarizes system calls made",
        "lsof: 'lsof -i :8080' finds process using specific port",
        "sar: System activity reporter - 'sar -u 1 5' for CPU over time",
        "vmstat: 'vmstat 1' reports virtual memory statistics",
        "dstat: Versatile replacement for vmstat, iostat, netstat",
        "glances: Comprehensive system monitor with web interface option",
        "pidstat: 'pidstat -r 1' shows memory usage per process over time",
        "tcpdump: 'sudo tcpdump -i any port 80' captures network packets",
        "time: 'time command' shows real/user/sys time for benchmarking",
    ],
    "vim_nano": [
        "Vim: 'ci(' changes text inside parentheses, works with {, [, \", '",
        "Vim: '.' repeats last change - powerful for repetitive edits",
        "Vim: 'gg=G' auto-indents entire file",
        "Vim: Ctrl+v for visual block mode - edit multiple lines at once",
        "Vim: ':set paste' before pasting to preserve formatting",
        "Vim: 'gf' opens file under cursor, Ctrl+o returns",
        "Vim: ':w !sudo tee %' saves file with sudo when you forgot",
        "Vim: 'qa' starts macro recording, 'q' stops, '@a' replays",
        "Nano: Alt+6 copies line, Ctrl+K cuts, Ctrl+U pastes",
        "Nano: Ctrl+W searches, Alt+W repeats search",
        "Nano: Alt+A marks text, then navigate to select",
        "Nano: Ctrl+T opens spell checker (if available)",
        "Nano: Alt+N disables/enables line wrapping",
        "Nano: Ctrl+_ goes to specific line number",
        "Micro: Modern nano alternative with mouse support and familiar keybindings",
    ],
    "security": [
        "Check permissions: 'ls -la' shows full permissions, 'stat file' for details",
        "Fix permissions: 'chmod 600 ~/.ssh/id_rsa' secures private keys",
        "Find SUID binaries: 'find / -perm -4000 2>/dev/null' lists setuid programs",
        "Show open ports: 'sudo ss -tulpn' or 'sudo netstat -tulpn'",
        "Firewall status: 'sudo ufw status verbose' on Ubuntu/Debian",
        "Check listening services: 'sudo lsof -i -P -n | grep LISTEN'",
        "GPG encrypt: 'gpg -c file' for symmetric, 'gpg -e -r recipient file' for asymmetric",
        "Generate passwords: 'openssl rand -base64 32' or 'pwgen -sy 16'",
        "Hash files: 'sha256sum file' to verify file integrity",
        "Secure delete: 'shred -vfz -n 3 file' overwrites before deletion",
        "SSH hardening: Disable root login and password auth in sshd_config",
        "Audit logs: 'sudo journalctl -xe' for system logs, 'last' for login history",
        "Check processes: 'ps aux --forest' shows process tree with users",
        "File capabilities: 'getcap file' shows special capabilities",
        "umask: Set to 077 for secure default file permissions",
    ],
    "networking": [
        "Test connectivity: 'ping -c 4 google.com' sends 4 packets",
        "Trace route: 'traceroute google.com' or 'mtr google.com' for interactive",
        "DNS lookup: 'dig @8.8.8.8 example.com' or 'nslookup example.com'",
        "Port check: 'nc -zv host 22' tests if port 22 is open",
        "Network interfaces: 'ip a' or 'ifconfig' shows all interfaces",
        "Routing table: 'ip route' or 'route -n' displays routes",
        "ARP cache: 'arp -a' shows IP to MAC address mappings",
        "Bandwidth test: 'curl -o /dev/null http://speedtest.tele2.net/1GB.zip'",
        "WiFi networks: 'nmcli dev wifi' lists available networks",
        "Connect WiFi: 'nmcli dev wifi connect SSID password pass'",
        "Show connections: 'nmcli con show' lists NetworkManager connections",
        "HTTP headers: 'curl -I https://example.com' shows response headers",
        "Download with resume: 'wget -c URL' or 'curl -C - -O URL'",
        "Network usage: 'vnstat' shows network traffic statistics",
        "Local network scan: 'nmap -sn 192.168.1.0/24' finds devices",
    ],
    "packages": [
        "APT: 'apt list --installed' shows all installed packages",
        "APT: 'apt-cache policy package' shows available versions",
        "APT: 'apt-mark showmanual' lists manually installed packages",
        "DNF/YUM: 'dnf history' shows transaction history with undo option",
        "Python venv: 'python -m venv env && source env/bin/activate'",
        "pip: 'pip freeze > requirements.txt' saves current packages",
        "npm: 'npm ci' for faster, reproducible installs from package-lock",
        "npm: 'npx package' runs package without installing globally",
        "Homebrew: 'brew bundle dump' creates Brewfile of installed packages",
        "Snap: 'snap list --all' shows all snaps including disabled",
        "Flatpak: 'flatpak list --app' shows only applications, not runtimes",
        "Build from source: './configure --prefix=$HOME/.local && make && make install'",
        "Check dependencies: 'ldd binary' shows shared library dependencies",
        "Alternative versions: 'update-alternatives --config java' switches versions",
        "Package contents: 'dpkg -L package' or 'rpm -ql package' lists files",
    ],
}


def get_random_tip() -> tuple[str, str]:
    """Get a random tip from a random category

    Returns:
        tuple: (category, tip) - The category name and tip text
    """
    import random

    category = random.choice(list(TIPS.keys()))  # noqa: S311
    tip = random.choice(TIPS[category])  # noqa: S311
    return category, tip


def get_tip_from_category(category: str) -> str:
    """Get a random tip from a specific category

    Args:
        category: The category to select from

    Returns:
        str: A random tip from that category, or empty string if category doesn't exist
    """
    import random

    if category in TIPS:
        return random.choice(TIPS[category])  # noqa: S311
    return ""
