[metadata]
exported_at = "2025-08-07T13:19:10-04:00"
hostname = "mathew-All-Series"
user = "mathew"
filter = "python"
tracking_period = "today + yesterday"
sort_method = "time"
directories_shown = 5

[summary]
total_directories = 1
total_visits = 1
total_time_seconds = 0
total_time_formatted = "0s"
total_commits = 0

[time_patterns]

[[directories]]
path = "~/python-packages/Django-Mercury-Performance-Testing"
visits = 1
time_seconds = 0
time_formatted = "0s"
last_visited = "today"
git_commits = 0

[directories.tools_used]
wfreq = 2
pytest = 1
git = 1
avn = 1

# Top Tools Analysis
# Shows where each tool is most frequently used

[tools.wfreq]
total_uses = 2
category = "tool"
directories = [
    { path = "~/python-packages/Django-Mercury-Performance-Testing", uses = 2, percentage = 100 },
]

[tools.pytest]
total_uses = 1
category = "testing"
directories = [
    { path = "~/python-packages/Django-Mercury-Performance-Testing", uses = 1, percentage = 100 },
]

[tools.git]
total_uses = 1
category = "version_control"
directories = [
    { path = "~/python-packages/Django-Mercury-Performance-Testing", uses = 1, percentage = 100 },
]

[tools.avn]
total_uses = 1
category = "tool"
directories = [
    { path = "~/python-packages/Django-Mercury-Performance-Testing", uses = 1, percentage = 100 },
]

# Navigation Patterns

